/* =====================================================================
   Devil's Lie — THEMES + LEVELS (single source of truth)
   Shared by the game (window.*) and the Node solvability verifier.
   Legend: # solid  S start  E exit  @ runaway-exit alt  ^ spike
           F fake floor  P popup  D falling shard  X crusher
           M fake exit  O fall-through  B decoy  H phantom gap(solid)
           L lava(deadly)  G fake lava(safe solid)
   ===================================================================== */
(function () {
  "use strict";

  const THEMES = [
    { sky:["#2a0f1e","#1a0e16","#0c0a14"], glow:"rgba(255,120,90,0.18)", orb:"#ffd9a0",
      mtnA:"rgba(70,28,40,0.55)", mtnB:"rgba(45,18,28,0.78)", sil:"rgba(22,10,16,0.85)",
      blk:["#3a2630","#4a323e","#412a34","#291a22"], spk:["#eef0f6","#9498a6"],
      ember:"rgba(255,150,80,0.55)", decor:"spikes", name:"Hellpit", haz:"blade" },
    { sky:["#0e2438","#0a1622","#06101a"], glow:"rgba(120,200,255,0.16)", orb:"#dcefff",
      mtnA:"rgba(40,70,100,0.5)", mtnB:"rgba(24,44,66,0.78)", sil:"rgba(14,26,40,0.85)",
      blk:["#27384a","#34495e","#2e3f52","#1d2a38"], spk:["#eaf4ff","#9fc0d8"],
      ember:"rgba(170,220,255,0.5)", decor:"crystals", name:"Frostbite", haz:"ice" },
    { sky:["#13281c","#0d1b13","#08120c"], glow:"rgba(120,220,120,0.14)", orb:"#dfffb0",
      mtnA:"rgba(34,70,40,0.5)", mtnB:"rgba(20,44,26,0.78)", sil:"rgba(12,26,16,0.85)",
      blk:["#2a3a26","#384c30","#324428","#1f2c1a"], spk:["#eef0e0","#9aa878"],
      ember:"rgba(180,255,150,0.45)", decor:"trees", name:"Overgrowth", haz:"thorn" },
    { sky:["#1c1730","#13101e","#0a0812"], glow:"rgba(220,120,255,0.16)", orb:"#d6c4ff",
      mtnA:"rgba(60,52,80,0.5)", mtnB:"rgba(38,32,54,0.78)", sil:"rgba(22,18,32,0.85)",
      blk:["#34304a","#46415f","#3c3854","#23203a"], spk:["#dfe2ee","#9a9ab8"],
      ember:"rgba(210,160,255,0.5)", decor:"gears", name:"The Machine", haz:"saw" },
    { sky:["#160a26","#0d0718","#04030a"], glow:"rgba(180,90,255,0.18)", orb:"#e6bcff",
      mtnA:"rgba(48,28,72,0.55)", mtnB:"rgba(30,16,48,0.8)", sil:"rgba(16,8,26,0.88)",
      blk:["#2e2444","#3e3058","#352a4c","#201838"], spk:["#f0d8ff","#b08ad0"],
      ember:"rgba(210,140,255,0.55)", decor:"shards", name:"The Void", haz:"crystal" },
    { sky:["#2e0a06","#1a0604","#0a0302"], glow:"rgba(255,120,40,0.22)", orb:"#ffcf8a",
      mtnA:"rgba(90,30,15,0.55)", mtnB:"rgba(60,18,8,0.8)", sil:"rgba(28,10,6,0.88)",
      blk:["#3a2018","#4a2a1e","#3e241a","#28140e"], spk:["#ffd9a0","#ff7a30"],
      ember:"rgba(255,140,50,0.6)", decor:"spikes", name:"Inferno", haz:"blade" },
    { sky:["#06222a","#04141a","#020a0e"], glow:"rgba(60,220,210,0.16)", orb:"#bdfff4",
      mtnA:"rgba(20,70,72,0.5)", mtnB:"rgba(12,44,46,0.8)", sil:"rgba(8,26,28,0.85)",
      blk:["#16383a","#1f4c4e","#1a4042","#0e2a2c"], spk:["#dffffb","#7fd8d0"],
      ember:"rgba(120,255,240,0.5)", decor:"crystals", name:"The Abyss", haz:"crystal" },
    { sky:["#1d2218","#12160e","#080a06"], glow:"rgba(190,210,120,0.14)", orb:"#eaf0c0",
      mtnA:"rgba(60,66,40,0.5)", mtnB:"rgba(40,44,26,0.8)", sil:"rgba(22,26,14,0.85)",
      blk:["#3a3a2e","#4a4a38","#40402f","#26261c"], spk:["#f0f0e0","#b8b8a0"],
      ember:"rgba(210,220,150,0.45)", decor:"trees", name:"Boneyard", haz:"blade" },
    { sky:["#101a36","#0a1024","#050814"], glow:"rgba(120,160,255,0.18)", orb:"#cfe0ff",
      mtnA:"rgba(40,50,100,0.5)", mtnB:"rgba(24,30,66,0.8)", sil:"rgba(14,18,40,0.85)",
      blk:["#27304a","#34405e","#2e3852","#1d2438"], spk:["#eaf0ff","#9fb0e8"],
      ember:"rgba(150,180,255,0.55)", decor:"gears", name:"Voltage", haz:"saw" },
    { sky:["#1a0610","#10040a","#040104"], glow:"rgba(255,40,90,0.2)", orb:"#ff9ab0",
      mtnA:"rgba(70,20,40,0.55)", mtnB:"rgba(44,10,24,0.82)", sil:"rgba(20,6,12,0.9)",
      blk:["#2e1420","#40202e","#361a26","#200e18"], spk:["#ffd0dc","#d06a86"],
      ember:"rgba(255,80,120,0.55)", decor:"shards", name:"Nightmare", haz:"crystal" },
  ];

  const LEVELS = [
    { name: "Just walk to the door", spd: 1.0,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    ^         E   ",
             "#############FF#####"],
      texts: [{c:3,t:"See? Totally normal. Just walk right \u2192"}, {c:11,t:"Almost there! Keep going\u2026"}] },

    { name: "Trust the floor", spd: 1.0,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "      #  #  #       ",
             "  S             P E ",
             "#####FFFFFFFFFF#####"],
      texts: [{c:5,t:"A nice solid bridge. Cross it \u2192"}, {c:13,t:"Ha. Should've taken the high road."}] },

    { name: "Look up. Look out.", spd: 1.0,
      grid: ["                    ",
             "      D   D    XX   ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S              M E ",
             "####################"],
      texts: [{c:2,t:"Easy corridor. Run to the EXIT \u2192"}, {c:14,t:"Door's right there. Trust me."}] },

    { name: "Spring a Leak", spd: 1.05,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    ^    P    M E ",
             "####################"],
      texts: [{c:2,t:"Spikes you can see. How quaint."}, {c:15,t:"Knock knock. (don't)"}] },

    { name: "Trapdoor", spd: 1.0, theme: 0,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S        M         ",
             "########  ##########",
             "                    ",
             "                    ",
             "          ^     E   ",
             "####################"],
      texts: [{c:1,t:"a door, right there. too easy, right? \ud83d\ude09"}, {c:8,t:"that's a TRAPDOOR. fall in \u2014 the real exit is downstairs."}, {c:13,t:"see? a whole basement. hop the spike. there's your door."}] },

    { name: "Double Cross", spd: 1.12,
      grid: ["                    ",
             "     D        XX    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P    P    M E ",
             "###FF####FF###FF####"],
      texts: [{c:1,t:"Three pits, three lies, a blade. Hop smart."}, {c:8,t:"feel the rhythm or feel the floor \ud83d\ude08"}, {c:14,t:"left door? cute."}] },

    { name: "Spike Garden", spd: 1.14,
      grid: ["                    ",
             "          D         ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S  ^   P   ^   M E ",
             "#########FF#########"],
      texts: [{c:1,t:"Mind the garden. It bites. Twice."}, {c:7,t:"shards on a timer now. tick tock."}, {c:15,t:"the door is lying. obviously."}] },

    { name: "The Big Lie", spd: 1.16,
      grid: ["                    ",
             "      D       XX    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S     P    P   M E ",
             "##FF####FF####FF####"],
      texts: [{c:1,t:"Halfway. EVERY trick at once."}, {c:7,t:"don't trust ANYTHING down here."}, {c:15,t:"final door. or is it. \ud83d\ude08"}] },

    { name: "First Burn", spd: 1.14,
      grid: ["                    ",
             "          D         ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S     P       M  E ",
             "####LL#####LL###LL##"],
      texts: [{c:1,t:"That orange glow? yeah. lava. don't."}, {c:6,t:"hop the molten gaps. shard overhead. casual."}, {c:14,t:"so close. so very hot."}] },

    { name: "Frostbite Finale", spd: 1.18,
      grid: ["                    ",
             "     D        XX    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P    ^    M E ",
             "###LL####FF###LL####"],
      texts: [{c:1,t:"Lava + fake floor + a blade. Goodbye."}, {c:8,t:"you're sweating. in a frost level. poetic."}, {c:15,t:"the REAL door survived the cold. you?"}] },

    { name: "Hall of Mirrors", spd: 1.16,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    BB   P    M E ",
             "########FF##########"],
      texts: [{c:2,t:"Scary spikes! Better jump them, right? \ud83d\ude44"}, {c:6,t:"\u2026or walk right through. They're fake, genius."}, {c:14,t:"THIS door's real. probably. maybe. \ud83d\ude0f"}] },

    { name: "Phantom Floor", spd: 1.16,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S              M E ",
             "####HHHHHH###FF#####"],
      texts: [{c:2,t:"A bottomless pit! Definitely don't walk in. \ud83d\ude08"}, {c:8,t:"\u2026it was floor the whole time. you're welcome."}, {c:12,t:"THIS gap is real though. (or is it \ud83d\ude43)"}] },

    { name: "Decoy Garden", spd: 1.2,
      grid: ["                    ",
             "             D      ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    B    P    M E ",
             "###HH####FF###HH####"],
      texts: [{c:1,t:"Trust nothing. Not the floor, not the rocks."}, {c:6,t:"that rock? fake. that gap? solid. \ud83e\udd21"}, {c:13,t:"blade incoming. you're rolling your eyes, I can tell."}] },

    { name: "Liar's Lagoon", spd: 1.2,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S  G    B    L M E ",
             "####GGG#####LL######"],
      texts: [{c:1,t:"Lava you can WALK on\u2026 and lava that'll kill you."}, {c:5,t:"the safe one looks exactly like the deadly one \ud83d\ude08"}, {c:14,t:"guess wrong = crispy. no pressure."}] },

    { name: "Green Hell", spd: 1.24,
      grid: ["                    ",
             "     D         D    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    B    P    M  E",
             "###HH####FF###LL####"],
      texts: [{c:1,t:"Jungle's end. Should be relaxing."}, {c:8,t:"lol no."}, {c:15,t:"so close. so very fake-close."}] },

    { name: "Backwards", spd: 1.18, rev: [6, 13],
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S              M E ",
             "#########FF#########"],
      texts: [{c:1,t:"Clean corridor. What could go wrong."}, {c:6,t:"wait\u2026 why is left now\u2014 \ud83d\ude43 (controls reversed!)"}, {c:14,t:"controls back to normal. eye-roll noted."}] },

    { name: "Now You See It", spd: 1.18,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S        E  M    @ ",
             "####################"],
      texts: [{c:1,t:"Door's right there. Walk over. Win. Easy."}, {c:8,t:"\ud83c\udfc3\ud83d\udca8 the EXIT just RAN AWAY. of course it did."}, {c:14,t:"not the fake door. chase the real one \u2192"}] },

    { name: "Double Trouble", spd: 1.24, rev: [10, 15],
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S      E    M    @ ",
             "######FF############"],
      texts: [{c:1,t:"Hop the gap, grab the door. simple."}, {c:7,t:"runaway door + reversed controls. you're SO welcome \ud83d\ude08"}, {c:13,t:"left is right, the door is gone. enjoy \ud83d\ude43"}] },

    { name: "Gears of Spite", spd: 1.2,
      grid: ["                    ",
             "    XX      D       ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S      P      P M E",
             "#########FF#########"],
      texts: [{c:1,t:"Mind the gears. And the saw. And the floor."}, {c:7,t:"a crusher, a sawblade, a fake door. relax."}, {c:15,t:"smug yet? almost."}] },

    { name: "Machine Finale", spd: 1.24, rev: [5, 9],
      grid: ["                    ",
             "     D         XX   ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S     B    E    M @",
             "##########FF########"],
      texts: [{c:1,t:"Reverse, fake rock, saw, runaway door. casual."}, {c:6,t:"rock = fake. now the door = RUNS. \ud83c\udfc3"}, {c:14,t:"one crusher between you and bragging rights."}] },

    { name: "Void Gate", spd: 1.3, rev: [6, 11],
      grid: ["                    ",
             "        D           ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S      P       M E ",
             "####FF####LL###FF###"],
      texts: [{c:1,t:"The Void. It's been waiting for you."}, {c:6,t:"controls reversed OVER lava. yeah \ud83d\ude08"}, {c:14,t:"deep breath. roll those eyes. jump."}] },

    { name: "Hide & Seek", spd: 1.3,
      grid: ["                    ",
             "      D       D     ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S   B   E   L  @  M",
             "###########LL#######"],
      texts: [{c:1,t:"Decoy rock, two shards, lava, a runaway door. go."}, {c:7,t:"and it's gone. \ud83c\udfc3 told you. catch it."}, {c:14,t:"M is a lie. the real one bolted right. \ud83d\ude44"}] },

    { name: "Springboard", spd: 1.3,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "           ^   E    ",
             "      ##########    ",
             "                    ",
             "                    ",
             " S            M     ",
             "####J###############"],
      texts: [{c:1,t:"the exit door? down here on the floor? how nice."}, {c:4,t:"BOUNCE \u2192 up is the only way now \ud83d\ude08"}, {c:11,t:"that floor door LIES. the real one floats up top."}] },

    { name: "The Basement", spd: 1.1, theme: 4,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S          M       ",
             "########  ##########",
             "                    ",
             "  #####       ####  ",
             "                    ",
             "                    ",
             "           ^^     E ",
             "####################"],
      texts: [{c:1,t:"An exit on the surface. how convenient. (it's a lie \ud83d\ude08)"}, {c:7,t:"the floor has a hole. DROP in \u2014 the real way is DOWN."}, {c:13,t:"welcome to the basement. mind the spikes. there's the door."}] },

    { name: "Trick Gate", spd: 1.2,
      grid: ["                    ",
             "        D           ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S t       T    M E ",
             "####################"],
      texts: [{c:1,t:"three doors ahead. one wins. one kills. one\u2026 surprises."}, {c:9,t:"that door? it sends you BACK to start \ud83c\udf00 hop over it."}, {c:15,t:"two doors left. one's the lie. choose \ud83d\ude08"}] },

    { name: "Welcome to Inferno", spd: 1.34,
      grid: ["                    ",
             "        D           ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P        P M E",
             "###LL#####LL###LL###"],
      texts: [{c:1,t:"Everything is lava. some of it is honest about it."}, {c:7,t:"the shard adds flavour. spicy flavour."}, {c:15,t:"the door survived. will you?"}] },

    { name: "Fire Walk With Me", spd: 1.34,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S  G   G    L  G E ",
             "###GGG###LL###GGG###"],
      texts: [{c:1,t:"Walk on the lava. trust me. (some of it \ud83d\ude08)"}, {c:5,t:"fake lava = floor. real lava = ashes. pick."}, {c:14,t:"feeling lucky? the door isn't."}] },

    { name: "Magma Rhythm", spd: 1.36,
      grid: ["                    ",
             "     D        D     ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P    P    M E ",
             "###LL####LL###LL####"],
      texts: [{c:1,t:"Lava gaps. Shards. One beat."}, {c:8,t:"this is basically dancing. deadly dancing."}, {c:15,t:"the floor lied. the lava didn't."}] },

    { name: "Eruption", spd: 1.36, rev: [8, 12],
      grid: ["                    ",
             "     D        XX    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P    G    M E ",
             "##LL####GGG###LL####"],
      texts: [{c:1,t:"Lava, crusher, fake lava, reverse. the works."}, {c:8,t:"controls flip ON the fake lava. cruel? yes."}, {c:15,t:"don't trust the glow. trust your eyes. maybe."}] },

    { name: "Inferno Finale", spd: 1.4,
      grid: ["                    ",
             "      D       D     ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P    G    P E ",
             "##LL####GGG###LL####"],
      texts: [{c:1,t:"Everything Inferno taught you. Faster."}, {c:8,t:"you're basically a fireball now. keep moving."}, {c:15,t:"the REAL door is past the LAST lie. always."}] },

    { name: "Into the Deep", spd: 1.36,
      grid: ["                    ",
             "     D         D    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    H    P    M E ",
             "####HH####FF########"],
      texts: [{c:1,t:"The deep dark. The gaps that aren't gaps."}, {c:6,t:"walk the phantom floor. crystals rain. fun."}, {c:15,t:"the door floats in the void. it's real. probably."}] },

    { name: "Phantom Tide", spd: 1.36,
      grid: ["                    ",
             "       D      D     ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S   H    H    M E  ",
             "###HH####HH##FF#####"],
      texts: [{c:1,t:"Every 'pit' here is solid. except where it isn't."}, {c:7,t:"one of these gaps is REAL. good luck. \ud83d\ude43"}, {c:15,t:"the last one's fake floor. the OPPOSITE trick."}] },

    { name: "The Ascent", spd: 1.4,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "          E         ",
             "      ##########    ",
             "                    ",
             "                    ",
             " S                  ",
             "###J##LLLL##########"],
      texts: [{c:1,t:"floor's molten ahead. no walking past THIS."}, {c:3,t:"hit the pad, ride it up out of the dark."}, {c:9,t:"the exit floats in the deep. climb to it."}] },

    { name: "Crystal Crush", spd: 1.4,
      grid: ["                    ",
             "  XX        D       ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P    H    M E ",
             "####FF###HH###LL####"],
      texts: [{c:1,t:"A crusher AND crystal shards. The Abyss shows off."}, {c:8,t:"phantom floor after the crusher. tasteful."}, {c:15,t:"smug? the door dares you."}] },

    { name: "Abyss Finale", spd: 1.44, rev: [12, 16],
      grid: ["                    ",
             "     D        XX    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S   H    P   G  M E",
             "###HH####LL##GGG####"],
      texts: [{c:1,t:"Phantom, crusher, lava, fake lava, reverse, shard."}, {c:8,t:"if you're not eye-rolling you're not paying attention."}, {c:15,t:"three worlds left. the gloves are OFF."}] },

    { name: "Rattle & Bone", spd: 1.42,
      grid: ["                    ",
             "   XX       XX      ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S  ^   P   ^   P E ",
             "#########FF#########"],
      texts: [{c:1,t:"Spikes like ribs. Crushers like jaws. Walk on."}, {c:8,t:"the bones remember everyone who rushed."}, {c:15,t:"the door's real. your confidence isn't."}] },

    { name: "Marrow Pits", spd: 1.44,
      grid: ["                    ",
             "      D       D     ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S   P   ^    P M E ",
             "##FF####FF###FF#####"],
      texts: [{c:1,t:"Three pits, two shards, a spike."}, {c:8,t:"a graveyard of players who mistimed this."}, {c:15,t:"the door's lying. you know this by now."}] },

    { name: "Bonewalk", spd: 1.44, rev: [6, 11],
      grid: ["                    ",
             "     D        XX    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S   B    P    M E  ",
             "###FF####LL###FF####"],
      texts: [{c:1,t:"Reverse over the marrow. Mind the decoy."}, {c:6,t:"left is right is wrong is dead. you know the drill \ud83d\ude08"}, {c:15,t:"the REAL exit waited politely. shoot it a glare."}] },

    { name: "Skull Crusher", spd: 1.46,
      grid: ["                    ",
             "  XX        XX      ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P     P   M E ",
             "####LL####FF###LL###"],
      texts: [{c:1,t:"Two crushers, marrow gaps. The Boneyard's pride."}, {c:8,t:"this is where rhythm goes to die. literally."}, {c:15,t:"survive the jaws, ignore the fake door."}] },

    { name: "Boneyard Finale", spd: 1.48, rev: [10, 15],
      grid: ["                    ",
             "     D        D     ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S  ^  P   G   P M E",
             "##FF###GGG###LL#####"],
      texts: [{c:1,t:"Spikes, shards, fake lava, lava, reverse."}, {c:8,t:"the finale before the finale before the finale."}, {c:15,t:"two worlds left. you've earned the nightmares."}] },

    { name: "Power On", spd: 1.44,
      grid: ["                    ",
             "    D      D        ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S     P      P M E ",
             "###FF####LL###FF####"],
      texts: [{c:1,t:"Sawblades on a wire. Time the gaps."}, {c:8,t:"it's basically a rhythm game. that kills you."}, {c:15,t:"the door's real. the floor sparks lies."}] },

    { name: "Short Circuit", spd: 1.46, rev: [5, 10],
      grid: ["                    ",
             "   XX       D       ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S   G    P    L M E",
             "###GGG###FF###LL####"],
      texts: [{c:1,t:"Reversed wiring. Fake lava. Real lava. A saw."}, {c:6,t:"the controls short out exactly where it hurts \ud83d\ude08"}, {c:15,t:"don't get fried. the door won't help."}] },

    { name: "Skyhook", spd: 1.5,
      grid: ["                    ",
             "              D     ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "          E         ",
             "      ##########    ",
             "                    ",
             "                    ",
             " S            M     ",
             "####J###############"],
      texts: [{c:1,t:"bounce up \u2014 and time the sawblade up top."}, {c:4,t:"the floor door's a decoy. the sky one's real."}, {c:10,t:"land clean. the saw doesn't forgive."}] },

    { name: "High Voltage", spd: 1.5, rev: [7, 13],
      grid: ["                    ",
             "   D       XX       ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P   G    L M E",
             "###FF###GGG##LL#####"],
      texts: [{c:1,t:"Max current. Reverse, saw, crusher, lava, fakes."}, {c:7,t:"flipped controls in the danger zone. classic us."}, {c:15,t:"the door survived the surge. barely. like you."}] },

    { name: "Voltage Finale", spd: 1.52,
      grid: ["                    ",
             "   D    XX     D    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P    L    M E ",
             "##FF####LL###FF#####"],
      texts: [{c:1,t:"Every saw, every crusher, every pit. ANGRY grid."}, {c:8,t:"one world left. the Nightmare wants a word."}, {c:15,t:"reach the door. prove the lies wrong. \u26a1"}] },

    { name: "Bad Dream", spd: 1.46, rev: [7, 12],
      grid: ["                    ",
             "     D        D     ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S  B   P   G   M E ",
             "##FF###GGG###LL#####"],
      texts: [{c:1,t:"Welcome to the Nightmare. It knows your tricks."}, {c:7,t:"reverse, decoy, fake lava, real lava. warm-up. \ud83d\ude08"}, {c:15,t:"the door is real. nothing else is."}] },

    { name: "Vertigo", spd: 1.52,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "           ^  E     ",
             "     ###########    ",
             "                    ",
             "                    ",
             " S        M         ",
             "###J##LL####GG######"],
      texts: [{c:1,t:"lava AND fake lava down here. don't bother \u2014 go UP."}, {c:3,t:"bounce, then thread the spikes on the ledge."}, {c:13,t:"vertigo's a lie too. the exit is real. probably."}] },

    { name: "The Undercroft", spd: 1.2, theme: 9,
      grid: ["                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S        M         ",
             "#########  #########",
             "                    ",
             "   #####     #####  ",
             "                    ",
             "                    ",
             "          ^^      E ",
             "##############LL####"],
      texts: [{c:2,t:"the door's up here, right? nope. it's BELOW. drop in \ud83d\ude08"}, {c:8,t:"the undercroft. spikes, then a lava moat, then the door."}, {c:15,t:"almost out. don't kiss the lava on the way."}] },

    { name: "The Long Dark", spd: 1.54, rev: [6, 10],
      grid: ["                    ",
             "   D    XX     D    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S  G    E    P M @ ",
             "##GGG###LL#######FF#"],
      texts: [{c:1,t:"Runaway door in the dark, every hazard, reversed."}, {c:6,t:"the door RUNS the moment you trust it. \ud83c\udfc3 obviously."}, {c:15,t:"chase it past the saws. earn the last level."}] },

    { name: "The Devil's Lie", spd: 1.58, rev: [5, 9],
      grid: ["                    ",
             "   D    XX     D    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             "                    ",
             " S    P   L   E  M @",
             "##FF###LL####FF#####"],
      texts: [{c:1,t:"The LAST lie. Everything. Reversed. On fire. Running."}, {c:5,t:"reversed. obviously. it's the finale. expect no mercy."}, {c:13,t:"the door RUNS. \ud83c\udfc3 one last sprint. then you've BEATEN the Devil."}] }
  ];

  const api = { THEMES: THEMES, LEVELS: LEVELS };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (typeof window !== "undefined") { window.THEMES = THEMES; window.LEVELS = LEVELS; }
})();
